name: VideoPlayer
options:
    bundleIdPrefix: com.state.VideoPlayer
    deploymentTarget:
        iOS: 13.0
targets:
    VideoPlayer:
        info:
            path: VideoPlayer/VideoPlayer/Info.plist
        settings:
            configs:
                Debug:
                    DEBUG_MODE: YES
                Release:
                    DEBUG_MODE: NO
        type: application
        platform: iOS
        sources:
            - path: VideoPlayer
 
    
